require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'

use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

  # Add Capacitor plugins below if needed
  # pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  # pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  # pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  # pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end

  assertDeploymentTarget(installer)
end